CREATE TABLE screens (
    id SERIAL PRIMARY KEY,
    slot1 VARCHAR(255),
    slot2 VARCHAR(255),
    slot3 VARCHAR(255),
    slot4 VARCHAR(255),
    slot5 VARCHAR(255)
);
CREATE TABLE playlist12 (
    id SERIAL PRIMARY KEY,
    pname VARCHAR(255) ,
    pdescription TEXT ,
    screenid INTEGER[] ,
    slot1 VARCHAR(255) ,
    slot1_updatetime TIMESTAMP ,
    slot1_deletetime TIMESTAMP ,
    slot1_update_status VARCHAR(50) DEFAULT 'pending',
    slot1_delete_status VARCHAR(50) DEFAULT 'pending',
    slot2 VARCHAR(255) ,
    slot2_updatetime TIMESTAMP ,
    slot2_deletetime TIMESTAMP ,
    slot2_update_status VARCHAR(50) DEFAULT 'pending',
    slot2_delete_status VARCHAR(50) DEFAULT 'pending',
    slot3 VARCHAR(255) ,
    slot3_updatetime TIMESTAMP ,
    slot3_deletetime TIMESTAMP ,
    slot3_update_status VARCHAR(50) DEFAULT 'pending',
    slot3_delete_status VARCHAR(50) DEFAULT 'pending',
    slot4 VARCHAR(255) ,
    slot4_updatetime TIMESTAMP ,
    slot4_deletetime TIMESTAMP ,
    slot4_update_status VARCHAR(50) DEFAULT 'pending',
    slot4_delete_status VARCHAR(50) DEFAULT 'pending',
    slot5 VARCHAR(255) ,
    slot5_updatetime TIMESTAMP ,
    slot5_deletetime TIMESTAMP ,
    slot5_update_status VARCHAR(50) DEFAULT 'pending',
    slot5_delete_status VARCHAR(50) DEFAULT 'pending'
);
