


CREATE TABLE IF NOT EXISTS public.playlists12345
(
    id SERIAL PRIMARY KEY,
    screen_id INTEGER[] ,
    playlistname character varying(255) ,
    playlistdescription text ,
    layout_1 character varying(255) , -- Added layout name
    slot1 character varying(255)[] ,
    slot1_updatetime TIMESTAMP ,
    slot1_deletetime TIMESTAMP , 
    slot1_update_status VARCHAR(50) DEFAULT 'pending',
    slot1_delete_status VARCHAR(50) DEFAULT 'pending',
slot2 character varying(255)[] ,
    slot2_updatetime TIMESTAMP ,
    slot2_deletetime TIMESTAMP , 
    slot2_update_status VARCHAR(50) DEFAULT 'pending',
    slot2_delete_status VARCHAR(50) DEFAULT 'pending',
 slot3 character varying(255)[] ,
    slot3_updatetime TIMESTAMP ,
    slot3_deletetime TIMESTAMP , 
    slot3_update_status VARCHAR(50) DEFAULT 'pending',
    slot3_delete_status VARCHAR(50) DEFAULT 'pending',
 slot4 character varying(255)[] ,
    slot4_updatetime TIMESTAMP ,
    slot4_deletetime TIMESTAMP , 
    slot4_update_status VARCHAR(50) DEFAULT 'pending',
    slot4_delete_status VARCHAR(50) DEFAULT 'pending',
slot5 character varying(255)[] ,
    slot5_updatetime TIMESTAMP ,
    slot5_deletetime TIMESTAMP , 
    slot5_update_status VARCHAR(50) DEFAULT 'pending',
    slot5_delete_status VARCHAR(50) DEFAULT 'pending',
slot6 character varying(255)[] ,
    slot6_updatetime TIMESTAMP ,
    slot6_deletetime TIMESTAMP , 
    slot6_update_status VARCHAR(50) DEFAULT 'pending',
    slot6_delete_status VARCHAR(50) DEFAULT 'pending',

slot7 character varying(255)[] ,
    slot7_updatetime TIMESTAMP ,
    slot7_deletetime TIMESTAMP , 
    slot7_update_status VARCHAR(50) DEFAULT 'pending',
    slot7_delete_status VARCHAR(50) DEFAULT 'pending',

slot8 character varying(255)[] ,
    slot8_updatetime TIMESTAMP ,
    slot8_deletetime TIMESTAMP , 
    slot8_update_status VARCHAR(50) DEFAULT 'pending',
    slot8_delete_status VARCHAR(50) DEFAULT 'pending',

slot9 character varying(255)[] ,
    slot9_updatetime TIMESTAMP ,
    slot9_deletetime TIMESTAMP , 
    slot9_update_status VARCHAR(50) DEFAULT 'pending',
    slot9_delete_status VARCHAR(50) DEFAULT 'pending',

slot10 character varying(255)[] ,
    slot10_updatetime TIMESTAMP ,
    slot10_deletetime TIMESTAMP , 
    slot10_update_status VARCHAR(50) DEFAULT 'pending',
    slot10_delete_status VARCHAR(50) DEFAULT 'pending',

slot11 character varying(255)[] ,
    slot11_updatetime TIMESTAMP ,
    slot11_deletetime TIMESTAMP , 
    slot11_update_status VARCHAR(50) DEFAULT 'pending',
    slot11_delete_status VARCHAR(50) DEFAULT 'pending',

slot12 character varying(255)[] ,
    slot12_updatetime TIMESTAMP ,
    slot12_deletetime TIMESTAMP , 
    slot12_update_status VARCHAR(50) DEFAULT 'pending',
    slot12_delete_status VARCHAR(50) DEFAULT 'pending',

slot13 character varying(255)[] ,
    slot13_updatetime TIMESTAMP ,
    slot13_deletetime TIMESTAMP , 
    slot13_update_status VARCHAR(50) DEFAULT 'pending',
    slot13_delete_status VARCHAR(50) DEFAULT 'pending',

slot14 character varying(255)[] ,
    slot14_updatetime TIMESTAMP ,
    slot14_deletetime TIMESTAMP , 
    slot14_update_status VARCHAR(50) DEFAULT 'pending',
    slot14_delete_status VARCHAR(50) DEFAULT 'pending',

slot15 character varying(255)[] ,
    slot15_updatetime TIMESTAMP ,
    slot15_deletetime TIMESTAMP , 
    slot15_update_status VARCHAR(50) DEFAULT 'pending',
    slot15_delete_status VARCHAR(50) DEFAULT 'pending',

slot16 character varying(255)[] ,
    slot16_updatetime TIMESTAMP ,
    slot16_deletetime TIMESTAMP , 
    slot16_update_status VARCHAR(50) DEFAULT 'pending',
    slot16_delete_status VARCHAR(50) DEFAULT 'pending',

slot17 character varying(255)[] ,
    slot17_updatetime TIMESTAMP ,
    slot17_deletetime TIMESTAMP , 
    slot17_update_status VARCHAR(50) DEFAULT 'pending',
    slot17_delete_status VARCHAR(50) DEFAULT 'pending',

slot18 character varying(255)[] ,
    slot18_updatetime TIMESTAMP ,
    slot18_deletetime TIMESTAMP , 
    slot18_update_status VARCHAR(50) DEFAULT 'pending',
    slot18_delete_status VARCHAR(50) DEFAULT 'pending',

slot19 character varying(255)[] ,
    slot19_updatetime TIMESTAMP ,
    slot19_deletetime TIMESTAMP , 
    slot19_update_status VARCHAR(50) DEFAULT 'pending',
    slot19_delete_status VARCHAR(50) DEFAULT 'pending',

slot20 character varying(255)[] ,
    slot20_updatetime TIMESTAMP ,
    slot20_deletetime TIMESTAMP , 
    slot20_update_status VARCHAR(50) DEFAULT 'pending',
    slot20_delete_status VARCHAR(50) DEFAULT 'pending',
slot21 character varying(255)[] ,
    slot21_updatetime TIMESTAMP ,
    slot21_deletetime TIMESTAMP , 
    slot21_update_status VARCHAR(50) DEFAULT 'pending',
    slot21_delete_status VARCHAR(50) DEFAULT 'pending',

slot22 character varying(255)[] ,
    slot22_updatetime TIMESTAMP ,
    slot22_deletetime TIMESTAMP , 
    slot22_update_status VARCHAR(50) DEFAULT 'pending',
    slot22_delete_status VARCHAR(50) DEFAULT 'pending',

slot23 character varying(255)[] ,
    slot23_updatetime TIMESTAMP ,
    slot23_deletetime TIMESTAMP , 
    slot23_update_status VARCHAR(50) DEFAULT 'pending',
    slot23_delete_status VARCHAR(50) DEFAULT 'pending',

slot24 character varying(255)[] ,
    slot24_updatetime TIMESTAMP ,
    slot24_deletetime TIMESTAMP , 
    slot24_update_status VARCHAR(50) DEFAULT 'pending',
    slot24_delete_status VARCHAR(50) DEFAULT 'pending',

slot25 character varying(255)[] ,
    slot25_updatetime TIMESTAMP ,
    slot25_deletetime TIMESTAMP , 
    slot25_update_status VARCHAR(50) DEFAULT 'pending',
    slot25_delete_status VARCHAR(50) DEFAULT 'pending',

slot26 character varying(255)[] ,
    slot26_updatetime TIMESTAMP ,
    slot26_deletetime TIMESTAMP , 
    slot26_update_status VARCHAR(50) DEFAULT 'pending',
    slot26_delete_status VARCHAR(50) DEFAULT 'pending',

slot27 character varying(255)[] ,
    slot27_updatetime TIMESTAMP ,
    slot27_deletetime TIMESTAMP , 
    slot27_update_status VARCHAR(50) DEFAULT 'pending',
    slot27_delete_status VARCHAR(50) DEFAULT 'pending',

slot28 character varying(255)[] ,
    slot28_updatetime TIMESTAMP ,
    slot28_deletetime TIMESTAMP , 
    slot28_update_status VARCHAR(50) DEFAULT 'pending',
    slot28_delete_status VARCHAR(50) DEFAULT 'pending',

slot29 character varying(255)[] ,
    slot29_updatetime TIMESTAMP ,
    slot29_deletetime TIMESTAMP , 
    slot29_update_status VARCHAR(50) DEFAULT 'pending',
    slot29_delete_status VARCHAR(50) DEFAULT 'pending',

slot30 character varying(255)[] ,
    slot30_updatetime TIMESTAMP ,
    slot30_deletetime TIMESTAMP , 
    slot30_update_status VARCHAR(50) DEFAULT 'pending',
    slot30_delete_status VARCHAR(50) DEFAULT 'pending',

slot31 character varying(255)[] ,
    slot31_updatetime TIMESTAMP ,
    slot31_deletetime TIMESTAMP , 
    slot31_update_status VARCHAR(50) DEFAULT 'pending',
    slot31_delete_status VARCHAR(50) DEFAULT 'pending',

slot32 character varying(255)[] ,
    slot32_updatetime TIMESTAMP ,
    slot32_deletetime TIMESTAMP , 
    slot32_update_status VARCHAR(50) DEFAULT 'pending',
    slot32_delete_status VARCHAR(50) DEFAULT 'pending',

slot33 character varying(255)[] ,
    slot33_updatetime TIMESTAMP ,
    slot33_deletetime TIMESTAMP , 
    slot33_update_status VARCHAR(50) DEFAULT 'pending',
    slot33_delete_status VARCHAR(50) DEFAULT 'pending',

slot34 character varying(255)[] ,
    slot34_updatetime TIMESTAMP ,
    slot34_deletetime TIMESTAMP , 
    slot34_update_status VARCHAR(50) DEFAULT 'pending',
    slot34_delete_status VARCHAR(50) DEFAULT 'pending',

slot35 character varying(255)[] ,
    slot35_updatetime TIMESTAMP ,
    slot35_deletetime TIMESTAMP , 
    slot35_update_status VARCHAR(50) DEFAULT 'pending',
    slot35_delete_status VARCHAR(50) DEFAULT 'pending',

slot36 character varying(255)[] ,
    slot36_updatetime TIMESTAMP ,
    slot36_deletetime TIMESTAMP , 
    slot36_update_status VARCHAR(50) DEFAULT 'pending',
    slot36_delete_status VARCHAR(50) DEFAULT 'pending',

slot37 character varying(255)[] ,
    slot37_updatetime TIMESTAMP ,
    slot37_deletetime TIMESTAMP , 
    slot37_update_status VARCHAR(50) DEFAULT 'pending',
    slot37_delete_status VARCHAR(50) DEFAULT 'pending',

slot38 character varying(255)[] ,
    slot38_updatetime TIMESTAMP ,
    slot38_deletetime TIMESTAMP , 
    slot38_update_status VARCHAR(50) DEFAULT 'pending',
    slot38_delete_status VARCHAR(50) DEFAULT 'pending',

slot39 character varying(255)[] ,
    slot39_updatetime TIMESTAMP ,
    slot39_deletetime TIMESTAMP , 
    slot39_update_status VARCHAR(50) DEFAULT 'pending',
    slot39_delete_status VARCHAR(50) DEFAULT 'pending',

slot40 character varying(255)[] ,
    slot40_updatetime TIMESTAMP ,
    slot40_deletetime TIMESTAMP , 
    slot40_update_status VARCHAR(50) DEFAULT 'pending',
    slot40_delete_status VARCHAR(50) DEFAULT 'pending',

slot41 character varying(255)[] ,
    slot41_updatetime TIMESTAMP ,
    slot41_deletetime TIMESTAMP , 
    slot41_update_status VARCHAR(50) DEFAULT 'pending',
    slot41_delete_status VARCHAR(50) DEFAULT 'pending',

slot42 character varying(255)[] ,
    slot42_updatetime TIMESTAMP ,
    slot42_deletetime TIMESTAMP , 
    slot42_update_status VARCHAR(50) DEFAULT 'pending',
    slot42_delete_status VARCHAR(50) DEFAULT 'pending',

slot43 character varying(255)[] ,
    slot43_updatetime TIMESTAMP ,
    slot43_deletetime TIMESTAMP , 
    slot43_update_status VARCHAR(50) DEFAULT 'pending',
    slot43_delete_status VARCHAR(50) DEFAULT 'pending',

slot44 character varying(255)[] ,
    slot44_updatetime TIMESTAMP ,
    slot44_deletetime TIMESTAMP , 
    slot44_update_status VARCHAR(50) DEFAULT 'pending',
    slot44_delete_status VARCHAR(50) DEFAULT 'pending',

slot45 character varying(255)[] ,
    slot45_updatetime TIMESTAMP ,
    slot45_deletetime TIMESTAMP , 
    slot45_update_status VARCHAR(50) DEFAULT 'pending',
    slot45_delete_status VARCHAR(50) DEFAULT 'pending',

slot46 character varying(255)[] ,
    slot46_updatetime TIMESTAMP ,
    slot46_deletetime TIMESTAMP , 
    slot46_update_status VARCHAR(50) DEFAULT 'pending',
    slot46_delete_status VARCHAR(50) DEFAULT 'pending',

slot47 character varying(255)[] ,
    slot47_updatetime TIMESTAMP ,
    slot47_deletetime TIMESTAMP , 
    slot47_update_status VARCHAR(50) DEFAULT 'pending',
    slot47_delete_status VARCHAR(50) DEFAULT 'pending',

slot48 character varying(255)[] ,
    slot48_updatetime TIMESTAMP ,
    slot48_deletetime TIMESTAMP , 
    slot48_update_status VARCHAR(50) DEFAULT 'pending',
    slot48_delete_status VARCHAR(50) DEFAULT 'pending',

slot49 character varying(255)[] ,
    slot49_updatetime TIMESTAMP ,
    slot49_deletetime TIMESTAMP , 
    slot49_update_status VARCHAR(50) DEFAULT 'pending',
    slot49_delete_status VARCHAR(50) DEFAULT 'pending',

slot50 character varying(255)[] ,
    slot50_updatetime TIMESTAMP ,
    slot50_deletetime TIMESTAMP , 
    slot50_update_status VARCHAR(50) DEFAULT 'pending',
    slot50_delete_status VARCHAR(50) DEFAULT 'pending',
slot51 character varying(255)[] ,
    slot51_updatetime TIMESTAMP ,
    slot51_deletetime TIMESTAMP , 
    slot51_update_status VARCHAR(50) DEFAULT 'pending',
    slot51_delete_status VARCHAR(50) DEFAULT 'pending',

slot52 character varying(255)[] ,
    slot52_updatetime TIMESTAMP ,
    slot52_deletetime TIMESTAMP , 
    slot52_update_status VARCHAR(50) DEFAULT 'pending',
    slot52_delete_status VARCHAR(50) DEFAULT 'pending',

slot53 character varying(255)[] ,
    slot53_updatetime TIMESTAMP ,
    slot53_deletetime TIMESTAMP , 
    slot53_update_status VARCHAR(50) DEFAULT 'pending',
    slot53_delete_status VARCHAR(50) DEFAULT 'pending',

slot54 character varying(255)[] ,
    slot54_updatetime TIMESTAMP ,
    slot54_deletetime TIMESTAMP , 
    slot54_update_status VARCHAR(50) DEFAULT 'pending',
    slot54_delete_status VARCHAR(50) DEFAULT 'pending',

slot55 character varying(255)[] ,
    slot55_updatetime TIMESTAMP ,
    slot55_deletetime TIMESTAMP , 
    slot55_update_status VARCHAR(50) DEFAULT 'pending',
    slot55_delete_status VARCHAR(50) DEFAULT 'pending',

slot56 character varying(255)[] ,
    slot56_updatetime TIMESTAMP ,
    slot56_deletetime TIMESTAMP , 
    slot56_update_status VARCHAR(50) DEFAULT 'pending',
    slot56_delete_status VARCHAR(50) DEFAULT 'pending',

slot57 character varying(255)[] ,
    slot57_updatetime TIMESTAMP ,
    slot57_deletetime TIMESTAMP , 
    slot57_update_status VARCHAR(50) DEFAULT 'pending',
    slot57_delete_status VARCHAR(50) DEFAULT 'pending',

slot58 character varying(255)[] ,
    slot58_updatetime TIMESTAMP ,
    slot58_deletetime TIMESTAMP , 
    slot58_update_status VARCHAR(50) DEFAULT 'pending',
    slot58_delete_status VARCHAR(50) DEFAULT 'pending',

slot59 character varying(255)[] ,
    slot59_updatetime TIMESTAMP ,
    slot59_deletetime TIMESTAMP , 
    slot59_update_status VARCHAR(50) DEFAULT 'pending',
    slot59_delete_status VARCHAR(50) DEFAULT 'pending',

slot60 character varying(255)[] ,
    slot60_updatetime TIMESTAMP ,
    slot60_deletetime TIMESTAMP , 
    slot60_update_status VARCHAR(50) DEFAULT 'pending',
    slot60_delete_status VARCHAR(50) DEFAULT 'pending',

slot61 character varying(255)[] ,
    slot61_updatetime TIMESTAMP ,
    slot61_deletetime TIMESTAMP , 
    slot61_update_status VARCHAR(50) DEFAULT 'pending',
    slot61_delete_status VARCHAR(50) DEFAULT 'pending',

slot62 character varying(255)[] ,
    slot62_updatetime TIMESTAMP ,
    slot62_deletetime TIMESTAMP , 
    slot62_update_status VARCHAR(50) DEFAULT 'pending',
    slot62_delete_status VARCHAR(50) DEFAULT 'pending',

slot63 character varying(255)[] ,
    slot63_updatetime TIMESTAMP ,
    slot63_deletetime TIMESTAMP , 
    slot63_update_status VARCHAR(50) DEFAULT 'pending',
    slot63_delete_status VARCHAR(50) DEFAULT 'pending',

slot64 character varying(255)[] ,
    slot64_updatetime TIMESTAMP ,
    slot64_deletetime TIMESTAMP , 
    slot64_update_status VARCHAR(50) DEFAULT 'pending',
    slot64_delete_status VARCHAR(50) DEFAULT 'pending',

slot65 character varying(255)[] ,
    slot65_updatetime TIMESTAMP ,
    slot65_deletetime TIMESTAMP , 
    slot65_update_status VARCHAR(50) DEFAULT 'pending',
    slot65_delete_status VARCHAR(50) DEFAULT 'pending',

slot66 character varying(255)[] ,
    slot66_updatetime TIMESTAMP ,
    slot66_deletetime TIMESTAMP , 
    slot66_update_status VARCHAR(50) DEFAULT 'pending',
    slot66_delete_status VARCHAR(50) DEFAULT 'pending',

slot67 character varying(255)[] ,
    slot67_updatetime TIMESTAMP ,
    slot67_deletetime TIMESTAMP , 
    slot67_update_status VARCHAR(50) DEFAULT 'pending',
    slot67_delete_status VARCHAR(50) DEFAULT 'pending',

slot68 character varying(255)[] ,
    slot68_updatetime TIMESTAMP ,
    slot68_deletetime TIMESTAMP , 
    slot68_update_status VARCHAR(50) DEFAULT 'pending',
    slot68_delete_status VARCHAR(50) DEFAULT 'pending',

slot69 character varying(255)[] ,
    slot69_updatetime TIMESTAMP ,
    slot69_deletetime TIMESTAMP , 
    slot69_update_status VARCHAR(50) DEFAULT 'pending',
    slot69_delete_status VARCHAR(50) DEFAULT 'pending',

slot70 character varying(255)[] ,
    slot70_updatetime TIMESTAMP ,
    slot70_deletetime TIMESTAMP , 
    slot70_update_status VARCHAR(50) DEFAULT 'pending',
    slot70_delete_status VARCHAR(50) DEFAULT 'pending',

slot71 character varying(255)[] ,
    slot71_updatetime TIMESTAMP ,
    slot71_deletetime TIMESTAMP , 
    slot71_update_status VARCHAR(50) DEFAULT 'pending',
    slot71_delete_status VARCHAR(50) DEFAULT 'pending',

slot72 character varying(255)[] ,
    slot72_updatetime TIMESTAMP ,
    slot72_deletetime TIMESTAMP , 
    slot72_update_status VARCHAR(50) DEFAULT 'pending',
    slot72_delete_status VARCHAR(50) DEFAULT 'pending',

slot73 character varying(255)[] ,
    slot73_updatetime TIMESTAMP ,
    slot73_deletetime TIMESTAMP , 
    slot73_update_status VARCHAR(50) DEFAULT 'pending',
    slot73_delete_status VARCHAR(50) DEFAULT 'pending',

slot74 character varying(255)[] ,
    slot74_updatetime TIMESTAMP ,
    slot74_deletetime TIMESTAMP , 
    slot74_update_status VARCHAR(50) DEFAULT 'pending',
    slot74_delete_status VARCHAR(50) DEFAULT 'pending',

slot75 character varying(255)[] ,
    slot75_updatetime TIMESTAMP ,
    slot75_deletetime TIMESTAMP , 
    slot75_update_status VARCHAR(50) DEFAULT 'pending',
    slot75_delete_status VARCHAR(50) DEFAULT 'pending',

slot76 character varying(255)[] ,
    slot76_updatetime TIMESTAMP ,
    slot76_deletetime TIMESTAMP , 
    slot76_update_status VARCHAR(50) DEFAULT 'pending',
    slot76_delete_status VARCHAR(50) DEFAULT 'pending',

slot77 character varying(255)[] ,
    slot77_updatetime TIMESTAMP ,
    slot77_deletetime TIMESTAMP , 
    slot77_update_status VARCHAR(50) DEFAULT 'pending',
    slot77_delete_status VARCHAR(50) DEFAULT 'pending',

slot78 character varying(255)[] ,
    slot78_updatetime TIMESTAMP ,
    slot78_deletetime TIMESTAMP , 
    slot78_update_status VARCHAR(50) DEFAULT 'pending',
    slot78_delete_status VARCHAR(50) DEFAULT 'pending',

slot79 character varying(255)[] ,
    slot79_updatetime TIMESTAMP ,
    slot79_deletetime TIMESTAMP , 
    slot79_update_status VARCHAR(50) DEFAULT 'pending',
    slot79_delete_status VARCHAR(50) DEFAULT 'pending',

slot80 character varying(255)[] ,
    slot80_updatetime TIMESTAMP ,
    slot80_deletetime TIMESTAMP , 
    slot80_update_status VARCHAR(50) DEFAULT 'pending',
    slot80_delete_status VARCHAR(50) DEFAULT 'pending',

slot81 character varying(255)[] ,
    slot81_updatetime TIMESTAMP ,
    slot81_deletetime TIMESTAMP , 
    slot81_update_status VARCHAR(50) DEFAULT 'pending',
    slot81_delete_status VARCHAR(50) DEFAULT 'pending',

slot82 character varying(255)[] ,
    slot82_updatetime TIMESTAMP ,
    slot82_deletetime TIMESTAMP , 
    slot82_update_status VARCHAR(50) DEFAULT 'pending',
    slot82_delete_status VARCHAR(50) DEFAULT 'pending',

slot83 character varying(255)[] ,
    slot83_updatetime TIMESTAMP ,
    slot83_deletetime TIMESTAMP , 
    slot83_update_status VARCHAR(50) DEFAULT 'pending',
    slot83_delete_status VARCHAR(50) DEFAULT 'pending',

slot84 character varying(255)[] ,
    slot84_updatetime TIMESTAMP ,
    slot84_deletetime TIMESTAMP , 
    slot84_update_status VARCHAR(50) DEFAULT 'pending',
    slot84_delete_status VARCHAR(50) DEFAULT 'pending',

slot85 character varying(255)[] ,
    slot85_updatetime TIMESTAMP ,
    slot85_deletetime TIMESTAMP , 
    slot85_update_status VARCHAR(50) DEFAULT 'pending',
    slot85_delete_status VARCHAR(50) DEFAULT 'pending',

slot86 character varying(255)[] ,
    slot86_updatetime TIMESTAMP ,
    slot86_deletetime TIMESTAMP , 
    slot86_update_status VARCHAR(50) DEFAULT 'pending',
    slot86_delete_status VARCHAR(50) DEFAULT 'pending',

slot87 character varying(255)[] ,
    slot87_updatetime TIMESTAMP ,
    slot87_deletetime TIMESTAMP , 
    slot87_update_status VARCHAR(50) DEFAULT 'pending',
    slot87_delete_status VARCHAR(50) DEFAULT 'pending',

slot88 character varying(255)[] ,
    slot88_updatetime TIMESTAMP ,
    slot88_deletetime TIMESTAMP , 
    slot88_update_status VARCHAR(50) DEFAULT 'pending',
    slot88_delete_status VARCHAR(50) DEFAULT 'pending',

slot89 character varying(255)[] ,
    slot89_updatetime TIMESTAMP ,
    slot89_deletetime TIMESTAMP , 
    slot89_update_status VARCHAR(50) DEFAULT 'pending',
    slot89_delete_status VARCHAR(50) DEFAULT 'pending',

slot90 character varying(255)[] ,
    slot90_updatetime TIMESTAMP ,
    slot90_deletetime TIMESTAMP , 
    slot90_update_status VARCHAR(50) DEFAULT 'pending',
    slot90_delete_status VARCHAR(50) DEFAULT 'pending',

slot91 character varying(255)[] ,
    slot91_updatetime TIMESTAMP ,
    slot91_deletetime TIMESTAMP , 
    slot91_update_status VARCHAR(50) DEFAULT 'pending',
    slot91_delete_status VARCHAR(50) DEFAULT 'pending',

slot92 character varying(255)[] ,
    slot92_updatetime TIMESTAMP ,
    slot92_deletetime TIMESTAMP , 
    slot92_update_status VARCHAR(50) DEFAULT 'pending',
    slot92_delete_status VARCHAR(50) DEFAULT 'pending',

slot93 character varying(255)[] ,
    slot93_updatetime TIMESTAMP ,
    slot93_deletetime TIMESTAMP , 
    slot93_update_status VARCHAR(50) DEFAULT 'pending',
    slot93_delete_status VARCHAR(50) DEFAULT 'pending',

slot94 character varying(255)[] ,
    slot94_updatetime TIMESTAMP ,
    slot94_deletetime TIMESTAMP , 
    slot94_update_status VARCHAR(50) DEFAULT 'pending',
    slot94_delete_status VARCHAR(50) DEFAULT 'pending',

slot95 character varying(255)[] ,
    slot95_updatetime TIMESTAMP ,
    slot95_deletetime TIMESTAMP , 
    slot95_update_status VARCHAR(50) DEFAULT 'pending',
    slot95_delete_status VARCHAR(50) DEFAULT 'pending',

slot96 character varying(255)[] ,
    slot96_updatetime TIMESTAMP ,
    slot96_deletetime TIMESTAMP , 
    slot96_update_status VARCHAR(50) DEFAULT 'pending',
    slot96_delete_status VARCHAR(50) DEFAULT 'pending',

slot97 character varying(255)[] ,
    slot97_updatetime TIMESTAMP ,
    slot97_deletetime TIMESTAMP , 
    slot97_update_status VARCHAR(50) DEFAULT 'pending',
    slot97_delete_status VARCHAR(50) DEFAULT 'pending',

slot98 character varying(255)[] ,
    slot98_updatetime TIMESTAMP ,
    slot98_deletetime TIMESTAMP , 
    slot98_update_status VARCHAR(50) DEFAULT 'pending',
    slot98_delete_status VARCHAR(50) DEFAULT 'pending',

slot99 character varying(255)[] ,
    slot99_updatetime TIMESTAMP ,
    slot99_deletetime TIMESTAMP , 
    slot99_update_status VARCHAR(50) DEFAULT 'pending',
    slot99_delete_status VARCHAR(50) DEFAULT 'pending',

slot100 character varying(255)[] ,
    slot100_updatetime TIMESTAMP ,
    slot100_deletetime TIMESTAMP , 
    slot100_update_status VARCHAR(50) DEFAULT 'pending',
    slot100_delete_status VARCHAR(50) DEFAULT 'pending')

